package cmd

import (
	"fmt"
	"html"
	"sort"
	"strings"

	"github.com/retrofilter/rf/core"
	"github.com/retrofilter/rf/eval"
	"github.com/retrofilter/rf/llm"
	"github.com/retrofilter/rf/models/schema"
	"github.com/spf13/cobra"
)

var handbookCmd = &cobra.Command{
	Use:    "handbook",
	Short:  "print HANDBOOK.md content generated from the command registry",
	Hidden: true,
	Args:   cobra.NoArgs,
	RunE: func(cmd *cobra.Command, args []string) error {
		text, err := generateHandbook()
		if err != nil {
			return err
		}
		fmt.Print(text)
		return nil
	},
}

var sitedocsCmd = &cobra.Command{
	Use:    "sitedocs",
	Short:  "print site/docs.html content generated from the command registry",
	Hidden: true,
	Args:   cobra.NoArgs,
	RunE: func(cmd *cobra.Command, args []string) error {
		text, err := generateSiteDocsPage()
		if err != nil {
			return err
		}
		fmt.Print(text)
		return nil
	},
}

func init() {
	rootCmd.AddCommand(handbookCmd)
	rootCmd.AddCommand(sitedocsCmd)
}

func generateHandbook() (string, error) {
	closeRegistry, err := bootCommandRegistry()
	if err != nil {
		return "", err
	}
	defer closeRegistry()

	commands := eval.CommandWords()
	sort.Strings(commands)
	isCommand := map[string]bool{}
	for _, name := range commands {
		isCommand[name] = true
	}
	var stageOnly []string
	for _, name := range eval.StageWords() {
		if !isCommand[name] {
			stageOnly = append(stageOnly, name)
		}
	}
	sort.Strings(stageOnly)

	var b strings.Builder
	b.WriteString("# HANDBOOK\n\n")
	b.WriteString("<!-- generated by `make handbook` from the command registry — edit the\n")
	b.WriteString("     eval.Register declarations beside each builtin, not this file -->\n\n")
	b.WriteString("Command mode's vocabulary: every word here is safe to type at the prompt —\n")
	b.WriteString("no name that shadows a system binary appears (`ls`, `grep`, `cat`, ... always\n")
	b.WriteString("mean the real programs; the Scheme spellings stay reachable with parens).\n")
	b.WriteString("Every command answers `-h`/`--help` with its short usage; `help` opens the\n")
	b.WriteString("man-formatted manual at the prompt — `help <command>` is that command's man\n")
	b.WriteString("page, `help --list | grep rank` filters the pages as rows. `(builtins)` lists\n")
	b.WriteString("every callable including the Scheme library.\n\n")

	b.WriteString("## Commands\n\n")
	b.WriteString("Stage means the word is also valid after a `|`, the piped value threading\n")
	b.WriteString("in as the last argument.\n\n")
	b.WriteString("| command | stage | description |\n|---|---|---|\n")
	for _, name := range commands {
		meta, _ := eval.LookupCommand(name)
		stage := ""
		if meta.Stage {
			stage = "✓"
		}
		fmt.Fprintf(&b, "| %s | %s | %s |\n", name, stage, tableCell(eval.BuiltinDoc(name)))
	}

	b.WriteString("\n## Pipeline-only stages\n\n")
	b.WriteString("Valid after a `|` but not as a line's first word.\n\n")
	b.WriteString("| stage | description |\n|---|---|\n")
	for _, name := range stageOnly {
		fmt.Fprintf(&b, "| %s | %s |\n", name, tableCell(eval.BuiltinDoc(name)))
	}

	b.WriteString("\n## Scheme library\n\n")
	b.WriteString("The rest of `(builtins)` — every registered function with no command-mode\n")
	b.WriteString("presence, callable with parens in any mode; `help <name>` at the prompt.\n\n")
	b.WriteString("| function | description |\n|---|---|\n")
	for _, name := range libraryWords() {
		fmt.Fprintf(&b, "| %s | %s |\n", name, tableCell(eval.BuiltinDoc(name)))
	}

	b.WriteString("\n## Reference\n")
	for _, name := range commands {
		text, ok := eval.CommandHelp(name)
		if !ok {
			continue
		}
		fmt.Fprintf(&b, "\n### %s\n\n```\n%s\n```\n", name, text)
	}
	return b.String(), nil
}

func tableCell(s string) string {
	return strings.ReplaceAll(s, "|", "\\|")
}

func libraryWords() []string {
	var library []string
	for _, name := range eval.RegisteredWords() {
		meta, _ := eval.LookupCommand(name)
		if !meta.Command && !meta.Stage {
			library = append(library, name)
		}
	}
	sort.Strings(library)
	return library
}

func bootCommandRegistry() (func(), error) {
	db, err := schema.OpenDB(":memory:")
	if err != nil {
		return nil, err
	}
	if err := schema.CreateTables(db); err != nil {
		db.Close()
		return nil, err
	}
	gs := core.NewGraphStore(db)
	chat, err := llm.NewChatWithConfig(gs, llm.Config{})
	if err != nil {
		db.Close()
		return nil, err
	}
	registerShellCommands(&shellState{chat: chat})
	return func() { db.Close() }, nil
}

func generateSiteDocsPage() (string, error) {
	closeRegistry, err := bootCommandRegistry()
	if err != nil {
		return "", err
	}
	defer closeRegistry()

	commands := eval.CommandWords()
	sort.Strings(commands)
	isCommand := map[string]bool{}
	for _, name := range commands {
		isCommand[name] = true
	}
	var stageOnly []string
	for _, name := range eval.StageWords() {
		if !isCommand[name] {
			stageOnly = append(stageOnly, name)
		}
	}
	sort.Strings(stageOnly)

	esc := html.EscapeString
	var b strings.Builder

	b.WriteString(`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>retro𝑓ilter manual</title>
<meta name="description" content="The retro𝑓ilter manual: every topic page and every command's man page, generated from the shell's command registry.">
<meta name="color-scheme" content="light dark">
<meta name="theme-color" media="(prefers-color-scheme: light)" content="#F1F0EA">
<meta name="theme-color" media="(prefers-color-scheme: dark)" content="#141413">
<link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Cstyle%3Etext%7Bfill:%23131313%7D@media(prefers-color-scheme:dark)%7Btext%7Bfill:%23ECEAE2%7D%7D%3C/style%3E%3Ctext x='32' y='47' text-anchor='middle' font-size='46' font-family='Georgia,serif'%3E%F0%9D%91%9F%F0%9D%91%93%3C/text%3E%3C/svg%3E">
<link rel="stylesheet" href="style.css">
</head>
<body>
<!-- generated by 'make site' from the command registry — edit the
     eval.Register declarations and docs/GUIDE.md, not this file -->
` + siteHeader("docs") + `

<main id="top">

  <section class="pane" id="index">
    <h2><span class="cmdlabel">Command:</span> Help</h2>
    <p class="docs-note">The same manual <code>help</code> opens at the prompt. Every row is a page — follow it for the full man rendering.</p>
    <div class="docs">
`)

	b.WriteString("<div class=\"doc-group\">\n<table>\n")
	for _, slug := range topicSlugs() {
		fmt.Fprintf(&b, "<tr><td><a href=\"#%s\">%s(7)</a></td><td>%s</td></tr>\n", esc(slug), esc(slug), esc(topicDocs[slug]))
	}
	b.WriteString("</table>\n<div class=\"pane-strip\"><b>Topics</b> — longer-form pages: <code>help &lt;topic&gt;</code></div>\n</div>\n")

	b.WriteString("<div class=\"doc-group\">\n<table>\n")
	for _, name := range commands {
		meta, _ := eval.LookupCommand(name)
		stage := ""
		if meta.Stage {
			stage = "|"
		}
		fmt.Fprintf(&b, "<tr><td><a href=\"#%s\">%s(1)</a></td><td class=\"st\">%s</td><td>%s</td></tr>\n", esc(name), esc(name), stage, esc(eval.BuiltinDoc(name)))
	}
	b.WriteString("</table>\n<div class=\"pane-strip\"><b>Commands</b> — a man page each: <code>help &lt;command&gt;</code>; <code>|</code> marks a word also valid after a pipe</div>\n</div>\n")

	b.WriteString("<div class=\"doc-group\">\n<table>\n")
	for _, name := range stageOnly {
		fmt.Fprintf(&b, "<tr><td><a href=\"#%s\">%s(1)</a></td><td class=\"st\">|</td><td>%s</td></tr>\n", esc(name), esc(name), esc(eval.BuiltinDoc(name)))
	}
	b.WriteString("</table>\n<div class=\"pane-strip\"><b>Pipeline stages</b> — valid after a <code>|</code> but not as a line's first word</div>\n</div>\n")

	b.WriteString("<div class=\"doc-group\" id=\"scheme\">\n<table>\n")
	for _, name := range libraryWords() {
		fmt.Fprintf(&b, "<tr><td>%s</td><td>%s</td></tr>\n", esc(name), esc(eval.BuiltinDoc(name)))
	}
	b.WriteString("</table>\n<div class=\"pane-strip\"><b>Scheme library</b> — the rest of <code>(builtins)</code>, callable with parens in any mode; <code>help &lt;name&gt;</code> at the prompt</div>\n</div>\n")

	b.WriteString("    </div>\n  </section>\n\n  <section class=\"pane\" id=\"pages\">\n")

	writeMan := func(name string) error {
		text, err := manPage(name, false)
		if err != nil {
			return err
		}
		fmt.Fprintf(&b, "<article class=\"man\" id=\"%s\">\n<a class=\"man-index\" href=\"#top\">index</a>\n<pre>%s</pre>\n</article>\n", esc(name), esc(strings.TrimRight(text, "\n")))
		return nil
	}
	for _, slug := range topicSlugs() {
		if err := writeMan(slug); err != nil {
			return "", err
		}
	}
	for _, name := range commands {
		if err := writeMan(name); err != nil {
			return "", err
		}
	}
	for _, name := range stageOnly {
		if err := writeMan(name); err != nil {
			return "", err
		}
	}

	b.WriteString("  </section>\n\n</main>\n\n" + siteFooter() + "</body>\n</html>\n")
	return b.String(), nil
}

func siteHeader(active string) string {
	docs := `<a href="docs.html">Docs</a>`
	home := ""
	if active == "docs" {
		docs = `<a href="#top" aria-current="page">Docs</a>`
		home = `<a href="index.html">Home</a>
    `
	}
	return `<header class="pane pane-title">
  <a class="wordmark" href="index.html">retro<i>filter</i></a>
  <nav aria-label="pages">
    ` + home + docs + `
    <a class="gh" href="https://github.com/retrofilter/rf" aria-label="retrofilter on GitHub"><svg viewBox="0 0 16 16" width="18" height="18" aria-hidden="true"><path fill="currentColor" d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27s1.36.09 2 .27c1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0 0 16 8c0-4.42-3.58-8-8-8Z"/></svg></a>
  </nav>
</header>`
}

func siteFooter() string {
	return `<footer class="pane pane-status">
  <a href="https://github.com/retrofilter/rf">github.com/retrofilter/rf</a>
  <span class="spacer"></span>
  <a href="https://github.com/retrofilter/rf/issues">Feedback</a>
  <span>MIT Licensed</span>
</footer>
`
}
